"""empty message

Revision ID: 0fe710dcb9eb
Revises: 9ea731b7dc71
Create Date: 2026-02-04 21:16:44.350896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe710dcb9eb'
down_revision = '9ea731b7dc71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('passworn', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('barbershop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'owner', ['owner_id'], ['id'])

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('owner_barbershop_id_fkey'), type_='foreignkey')
        batch_op.drop_column('barbershop_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbershop_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('owner_barbershop_id_fkey'), 'barbershop', ['barbershop_id'], ['id'])

    with op.batch_alter_table('barbershop', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')

    op.drop_table('admin_user')
    # ### end Alembic commands ###
