"""empty message

Revision ID: 149515a32e7a
Revises: 0fe710dcb9eb
Create Date: 2026-02-04 21:20:47.191270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149515a32e7a'
down_revision = '0fe710dcb9eb'
branch_labels = None
depends_on = None


def upgrade():
    # 1️⃣ Crear un owner por defecto (si no existe)
    op.execute("""
        INSERT INTO owner (name, email, phone, password)
        SELECT 'Default Owner', 'default@owner.com', '000000000', 'temp'
        WHERE NOT EXISTS (SELECT 1 FROM owner WHERE id = 1);
    """)

    # 2️⃣ Rellenar los NULL
    op.execute("""
        UPDATE barbershop
        SET owner_id = 1
        WHERE owner_id IS NULL;
    """)

    # 3️⃣ Ahora sí: NOT NULL
    with op.batch_alter_table('barbershop') as batch_op:
        batch_op.alter_column(
            'owner_id',
            existing_type=sa.INTEGER(),
            nullable=False
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbershop', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
