"""empty message

Revision ID: 1e86615428b2
Revises: f08c0f9354bb
Create Date: 2026-02-11 06:28:44.201126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e86615428b2'
down_revision = 'f08c0f9354bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barber_profile_image', sa.String(length=255), nullable=True))
        batch_op.drop_column('barber_image')

    with op.batch_alter_table('barber_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_demo_image', sa.String(length=255), nullable=True))
        batch_op.drop_column('service_image')

    with op.batch_alter_table('barbershop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbershop_image', sa.String(length=255), nullable=True))
        batch_op.drop_column('local_image')

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_profile_image', sa.String(length=255), nullable=True))
        batch_op.drop_column('owner_image')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_profile_image', sa.String(length=255), nullable=True))
        batch_op.drop_column('client_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('client_profile_image')

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('owner_profile_image')

    with op.batch_alter_table('barbershop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('barbershop_image')

    with op.batch_alter_table('barber_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('service_demo_image')

    with op.batch_alter_table('barber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barber_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('barber_profile_image')

    # ### end Alembic commands ###
