"""empty message

Revision ID: 2660ce02b50a
Revises: 1658c00f2cde
Create Date: 2026-02-01 21:51:15.185945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2660ce02b50a'
down_revision = '1658c00f2cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('barbershop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barbershop_id'], ['barbershop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barber')
    # ### end Alembic commands ###
