"""empty message

Revision ID: 2c7594cc0a97
Revises: 5cbf76930474
Create Date: 2026-02-18 07:14:16.958929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7594cc0a97'
down_revision = '5cbf76930474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('result_url', sa.String(length=500), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(length=200), nullable=True),
    sa.Column('lightx_order_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_image')
    # ### end Alembic commands ###
