"""empty message

Revision ID: 329006d19d44
Revises: 61f04f2746b6
Create Date: 2026-02-15 12:14:22.710839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329006d19d44'
down_revision = '61f04f2746b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbershop_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'barbershop', ['barbershop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbershop_id')

    # ### end Alembic commands ###
