"""empty message

Revision ID: 35c23a3e5a53
Revises: 5c8de5bd9baa
Create Date: 2026-02-22 19:36:45.455584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c23a3e5a53'
down_revision = '5c8de5bd9baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.alter_column('active_subscription',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.alter_column('active_subscription',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
