"""empty message

Revision ID: 477fb72b5c50
Revises: cacefe3395ea
Create Date: 2026-02-01 23:02:12.895257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477fb72b5c50'
down_revision = 'cacefe3395ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column(
            'start_time',
            existing_type=sa.VARCHAR(),
            type_=sa.Time(),
            existing_nullable=False,
            postgresql_using="start_time::time"
        )
        batch_op.alter_column(
            'end_time',
            existing_type=sa.VARCHAR(),
            type_=sa.Time(),
            existing_nullable=False,
            postgresql_using="end_time::time"
        )
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column(
            'end_time',
            existing_type=sa.Time(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            postgresql_using="end_time::varchar"
        )
        batch_op.alter_column(
            'start_time',
            existing_type=sa.Time(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            postgresql_using="start_time::varchar"
        )
    # ### end Alembic commands ###
