"""empty message

Revision ID: 5c8de5bd9baa
Revises: d204cd64486f
Create Date: 2026-02-22 19:35:41.021949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8de5bd9baa'
down_revision = 'd204cd64486f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_subscription', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stripe_owner_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_column('subscription_id')
        batch_op.drop_column('stripe_owner_id')
        batch_op.drop_column('active_subscription')

    # ### end Alembic commands ###
