"""empty message

Revision ID: 5fe3db06433b
Revises: 35c23a3e5a53
Create Date: 2026-02-22 22:01:29.173152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe3db06433b'
down_revision = '35c23a3e5a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_subscription', sa.Boolean(), nullable=True))
        batch_op.drop_column('active_suscription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_suscription', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('active_subscription')

    # ### end Alembic commands ###
