"""empty message

Revision ID: 6a96e8c098f4
Revises: 2bee77ed3295
Create Date: 2026-02-08 18:42:19.949760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a96e8c098f4'
down_revision = '2bee77ed3295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbershop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'barbershop', ['barbershop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbershop_id')

    # ### end Alembic commands ###
