"""empty message

Revision ID: 753d1baadd34
Revises: 329006d19d44
Create Date: 2026-02-15 14:41:28.073686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753d1baadd34'
down_revision = '329006d19d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbershop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbershop_description', sa.String(length=1500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbershop', schema=None) as batch_op:
        batch_op.drop_column('barbershop_description')

    # ### end Alembic commands ###
