"""empty message

Revision ID: 89874052aad1
Revises: 987be67191b8
Create Date: 2026-02-05 21:41:24.542426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89874052aad1'
down_revision = '987be67191b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barber', schema=None) as batch_op:
        batch_op.alter_column('barbershop_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barber', schema=None) as batch_op:
        batch_op.alter_column('barbershop_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
