"""empty message

Revision ID: 942280b76354
Revises: c4436502dd12
Create Date: 2026-02-08 11:41:41.176434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942280b76354'
down_revision = 'c4436502dd12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barber_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barber_service', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
