"""empty message

Revision ID: 987be67191b8
Revises: 9f443e5de9e6
Create Date: 2026-02-05 05:38:36.709951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987be67191b8'
down_revision = '9f443e5de9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.drop_column('passworn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passworn', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
