"""empty message

Revision ID: 9f443e5de9e6
Revises: 149515a32e7a
Create Date: 2026-02-04 21:35:13.347987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f443e5de9e6'
down_revision = '149515a32e7a'
branch_labels = None
depends_on = None


def upgrade():
    # 1️⃣ crear columna permitiendo NULL temporalmente
    with op.batch_alter_table('admin_user') as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))

    # 2️⃣ rellenar passwords viejas
    op.execute("""
        UPDATE admin_user
        SET password = 'temp123'
        WHERE password IS NULL
    """)

    # 3️⃣ ahora bloquear NOT NULL
    with op.batch_alter_table('admin_user') as batch_op:
        batch_op.alter_column('password', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
