"""empty message

Revision ID: a87626d6529e
Revises: a4806de966ac
Create Date: 2026-02-18 09:57:15.906576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87626d6529e'
down_revision = 'a4806de966ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barber_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barber_service', schema=None) as batch_op:
        batch_op.drop_column('service_description')

    # ### end Alembic commands ###
