"""empty message

Revision ID: b27f87cadff9
Revises: 8d03de69e660
Create Date: 2026-02-08 12:03:23.877392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27f87cadff9'
down_revision = '8d03de69e660'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Limpiamos las tablas para que no haya datos viejos que causen conflictos de NULL
    op.execute('TRUNCATE TABLE appointment, barber_service, service RESTART IDENTITY CASCADE')

    # 2. Rompemos las restricciones (por si acaso queda alguna)
    op.execute('ALTER TABLE appointment DROP CONSTRAINT IF EXISTS appointment_service_id_fkey CASCADE')
    op.execute('ALTER TABLE barber_service DROP CONSTRAINT IF EXISTS barber_service_service_id_fkey CASCADE')

    # 3. Ahora sí, modificamos 'appointment'
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        # Al estar la tabla vacía por el TRUNCATE, el NOT NULL ya no fallará
        batch_op.add_column(sa.Column('barber_service_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'barber_service', ['barber_service_id'], ['id'])
        batch_op.drop_column('service_id')

    # 4. Modificamos 'barber_service'
    with op.batch_alter_table('barber_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_column('service_id')

    # 5. Borramos la tabla vieja
    op.drop_table('service')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barber_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('barber_service_service_id_fkey'), 'service', ['service_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('appointment_service_id_fkey'), 'service', ['service_id'], ['id'])
        batch_op.drop_column('barber_service_id')

    op.create_table('service',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('barbershop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['barbershop_id'], ['barbershop.id'], name=op.f('service_barbershop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('service_pkey'))
    )
    # ### end Alembic commands ###
