"""empty message

Revision ID: b7c7b44f9171
Revises: 6a96e8c098f4
Create Date: 2026-02-10 16:49:12.829303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c7b44f9171'
down_revision = '6a96e8c098f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('schedule_barber_barbershop_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'barber_barbershop', ['barber_barbershop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('schedule_barber_barbershop_id_fkey'), 'barber_barbershop', ['barber_barbershop_id'], ['id'], ondelete='CASCADE')

    op.create_table('service',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('service_pkey'))
    )
    # ### end Alembic commands ###
