"""empty message

Revision ID: c4436502dd12
Revises: bb3a7b902774
Create Date: 2026-02-07 18:49:21.734291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4436502dd12'
down_revision = 'bb3a7b902774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barber_barbershop_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('schedule_barber_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'barber_barbershop', ['barber_barbershop_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('barber_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barber_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('schedule_barber_id_fkey'), 'barber', ['barber_id'], ['id'])
        batch_op.drop_column('barber_barbershop_id')

    # ### end Alembic commands ###
