"""empty message

Revision ID: d204cd64486f
Revises: 
Create Date: 2026-02-20 22:41:18.946765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd204cd64486f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('result_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('cloudinary_public_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('lightx_order_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('ai_image_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_image_pkey'))
    )
    # ### end Alembic commands ###
