"""empty message

Revision ID: f08c0f9354bb
Revises: fe74b66c52b3
Create Date: 2026-02-11 05:57:27.585435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08c0f9354bb'
down_revision = 'fe74b66c52b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barber_image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('barber_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('barbershop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_image', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('client_image')

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_column('owner_image')

    with op.batch_alter_table('barbershop', schema=None) as batch_op:
        batch_op.drop_column('local_image')

    with op.batch_alter_table('barber_service', schema=None) as batch_op:
        batch_op.drop_column('service_image')

    with op.batch_alter_table('barber', schema=None) as batch_op:
        batch_op.drop_column('barber_image')

    # ### end Alembic commands ###
