"""empty message

Revision ID: fe74b66c52b3
Revises: b7c7b44f9171
Create Date: 2026-02-10 21:13:52.425860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe74b66c52b3'
down_revision = 'b7c7b44f9171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barber', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
